/**
 * Aspose.HTML for Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef COM_ASPOSE_MODEL_IHttpBody_H_
#define COM_ASPOSE_MODEL_IHttpBody_H_


#include <iostream>

namespace com {
namespace aspose {
namespace model {

class  IHttpBody
{
public:
    virtual ~IHttpBody() { }

    virtual void writeTo( std::ostream& stream ) = 0;
};

}
}
}

#endif /* COM_ASPOSE_MODEL_IHttpBody_H_ */
